### ISSUE TITLE
Kartet viser ikke

### ISSUE THREAD

**Issue by askbk** [L4443/hikingapp#4]
funksjonen L er ikke definert, anonym

**Comment by LeikvollE** [comment]
Vises helt fint her...

**Comment by askbk** [comment]
Jeg får ReferenceError: L is not defined i map.js linje 3:5

**Comment by askbk** [comment]
Etter nærmere undersøkelser i QupZilla, Seamonkey og PaleMoon, ser det ut til at dette kun skjer med Firefox på denne PCen.

**Comment by LeikvollE** [comment]
Har du husket å åpne for eksterne javascript filer?

**Comment by askbk** [comment]
fant problemet: unpkg.com driver tracking og ble derfor blokkert av PrivacyBadger.
