### ISSUE TITLE
Startsted endrer seg

### ISSUE THREAD

**Issue by askbk** [L4443/hikingapp#5]
Startsted for turer til hytter endrer seg når man:
1. klikker på hytte A
2. klikker på hytte B
2. klikker på hytte B igjen
Hytte A får da startstedet til hytte B.

**Comment by LeikvollE** [comment]
Ruten som blir generert var mellom hytten som er valgt, og startstedet for hytten som ble trykket på (altså hytten som ble uvalgt).
